import { z } from "zod";
import { DEFAULT_LIMIT, GOOGLE_HEALTH_DATA_SOURCE_FAMILIES, GOOGLE_HEALTH_DATA_TYPE_SLUGS, MAX_GOOGLE_HEALTH_LIMIT } from "../constants.js";
import { AGENT_CLIENTS } from "../services/agent-manifest.js";

export const ResponseFormatSchema = z.enum(["markdown", "json"]).default("markdown");
export const AgentClientSchema = z.enum(AGENT_CLIENTS).default("generic");
export const PrivacyModeValueSchema = z.enum(["summary", "structured", "raw"]);
export const PrivacyModeSchema = PrivacyModeValueSchema.optional()
  .describe("Optional per-call privacy override. Defaults to GOOGLE_HEALTH_PRIVACY_MODE or structured. raw returns upstream Google Health JSON.");

export const DateSchema = z.string().regex(/^\d{4}-\d{2}-\d{2}$|^today$/).default("today");
export const DateTimeSchema = z.string().datetime({ offset: true }).describe("ISO 8601 date-time with timezone, e.g. 2026-05-01T00:00:00Z");
export const GoogleHealthDataTypeSchema = z.string()
  .regex(/^[a-z0-9][a-z0-9-]*$/)
  .describe(`Google Health data type in kebab case. Supported slugs (call google_health_list_data_types for units and which verbs each supports): ${GOOGLE_HEALTH_DATA_TYPE_SLUGS.join(", ")}. Other valid v4 kebab-case slugs are also accepted.`);
export const DataSourceFamilySchema = z.enum(GOOGLE_HEALTH_DATA_SOURCE_FAMILIES).optional();

export const SimpleReadInputSchema = z.object({
  privacy_mode: PrivacyModeSchema,
  response_format: ResponseFormatSchema
}).strict();

export const ResponseOnlyInputSchema = z.object({
  response_format: ResponseFormatSchema
}).strict();

export const CoverageInputSchema = z.object({
  live: z.boolean().default(false).describe("Default false. When true, calls read-only Google Health endpoints after OAuth setup and returns only redacted coverage status."),
  date: DateSchema,
  data_source_family: DataSourceFamilySchema,
  data_types: z.array(GoogleHealthDataTypeSchema).max(50).optional().describe("Optional subset of data_type slugs. Omit to validate the full local catalog."),
  response_format: ResponseFormatSchema
}).strict();

export const AgentManifestInputSchema = z.object({
  client: AgentClientSchema,
  response_format: ResponseFormatSchema
}).strict();

export const ConnectionStatusInputSchema = z.object({
  client: AgentClientSchema.optional(),
  response_format: ResponseFormatSchema
}).strict();

// Typed input contract for the planned (not-yet-registered) log_nutrition write tool. Defined now
// so the write gate, nutrient normalizer and v4 DataPoint mapper share one contract. Reuse this
// schema when the tool ships. See CONTRIBUTING.md → "Planned: nutrition write".
export const LogNutritionInputSchema = z.object({
  // free-text path OR explicit nutrients/food
  text: z.string().max(1000).optional().describe("Free-text meal, e.g. '2 ovos e 100g de arroz'. Resolved offline via estimateMeal."),
  food_name: z.string().max(200).optional(),
  meal_type: z.enum(["breakfast", "lunch", "dinner", "snack", "other"]).optional(),
  start_time: DateTimeSchema.optional(),
  end_time: DateTimeSchema.optional(),
  dry_run: z.boolean().default(true).describe("Default true. When true, validates and returns the would-be DataPoint body without POSTing."),
  explicit_user_intent: z.boolean().optional().describe("Must be true to persist a live write."),
  response_format: ResponseFormatSchema
}).strict();

export const AuthUrlInputSchema = z.object({
  state: z.string().max(500).optional().describe("Optional OAuth state value generated by the caller."),
  scopes: z.array(z.string()).optional().describe("Optional scope override. Defaults to read-only Google Health scopes used by this server."),
  response_format: ResponseFormatSchema
}).strict();

export const ExchangeCodeInputSchema = z.object({
  code: z.string().min(1).describe("OAuth authorization code, or a full redirect URL containing ?code=..."),
  response_format: ResponseFormatSchema
}).strict();

export const DataPointsInputSchema = z.object({
  data_type: GoogleHealthDataTypeSchema.default("steps"),
  filter: z.string().max(1000).optional().describe("Optional Google AIP-160 filter expression. Use snake_case field names in filters."),
  page_size: z.number().int().min(1).max(MAX_GOOGLE_HEALTH_LIMIT).default(DEFAULT_LIMIT),
  page_token: z.string().optional(),
  privacy_mode: PrivacyModeSchema,
  response_format: ResponseFormatSchema
}).strict();

export const GetDataPointInputSchema = z.object({
  data_type: GoogleHealthDataTypeSchema,
  data_point_id: z.string().min(1).max(500)
    .describe("Data point id, or the full resource name from a list/reconcile response (users/me/dataTypes/<type>/dataPoints/<id>)."),
  privacy_mode: PrivacyModeSchema,
  response_format: ResponseFormatSchema
}).strict();

export const PairedDevicesInputSchema = z.object({
  page_size: z.number().int().min(1).max(MAX_GOOGLE_HEALTH_LIMIT).optional(),
  page_token: z.string().optional(),
  privacy_mode: PrivacyModeSchema,
  response_format: ResponseFormatSchema
}).strict();

export const ReconcileInputSchema = DataPointsInputSchema.extend({
  data_source_family: DataSourceFamilySchema
}).strict();

export const DailyRollupInputSchema = z.object({
  data_type: GoogleHealthDataTypeSchema.default("steps"),
  start_date: DateSchema,
  end_date: DateSchema.optional().describe("Exclusive end date as YYYY-MM-DD. Defaults to the next day."),
  window_size_days: z.number().int().min(1).max(90).default(1),
  page_size: z.number().int().min(1).max(MAX_GOOGLE_HEALTH_LIMIT).default(DEFAULT_LIMIT),
  page_token: z.string().optional(),
  data_source_family: DataSourceFamilySchema,
  privacy_mode: PrivacyModeSchema,
  response_format: ResponseFormatSchema
}).strict();

export const RollupInputSchema = z.object({
  data_type: GoogleHealthDataTypeSchema.default("steps"),
  start_time: DateTimeSchema,
  end_time: DateTimeSchema,
  window_size: z.string().regex(/^\d+(\.\d+)?s$/).default("3600s").describe("Duration in protobuf seconds format, e.g. 3600s."),
  page_size: z.number().int().min(1).max(MAX_GOOGLE_HEALTH_LIMIT).default(DEFAULT_LIMIT),
  page_token: z.string().optional(),
  data_source_family: DataSourceFamilySchema,
  privacy_mode: PrivacyModeSchema,
  response_format: ResponseFormatSchema
}).strict();

export const DailySummaryInputSchema = z.object({
  date: DateSchema,
  timezone: z.string().min(1).max(80).default("UTC").describe("IANA timezone used only for display, e.g. America/New_York."),
  response_format: ResponseFormatSchema
}).strict();

export const WellnessContextInputSchema = z.object({
  days: z.number().int().min(1).max(30).default(7).describe("Lookback window for normalized Google Health wellness context."),
  timezone: z.string().min(1).max(80).default("UTC").describe("IANA timezone used only for display, e.g. America/New_York."),
  soreness: z.array(z.string().min(1).max(80)).default([]),
  injury_flags: z.array(z.string().min(1).max(120)).default([]),
  notes: z.string().max(500).optional(),
  response_format: ResponseFormatSchema
}).strict();

export const WeeklySummaryInputSchema = z.object({
  days: z.number().int().min(7).max(60).default(7).describe("Recent analysis window in days."),
  compare_days: z.number().int().min(0).max(60).default(7).describe("Prior comparison window in days. Use 0 to disable comparison."),
  timezone: z.string().min(1).max(80).default("UTC").describe("IANA timezone used only for display, e.g. America/New_York."),
  response_format: ResponseFormatSchema
}).strict();

export const AuthUrlOutputSchema = z.object({
  auth_url: z.string(),
  redirect_uri: z.string(),
  scopes: z.array(z.string()),
  next_step: z.string()
}).strict();

export const ExchangeCodeOutputSchema = z.object({
  ok: z.boolean(),
  token_path: z.string(),
  scope: z.string().optional(),
  expires_at: z.number().optional(),
  note: z.string()
}).strict();

export const EndpointDataOutputSchema = z.object({
  endpoint: z.string(),
  privacy_mode: PrivacyModeValueSchema,
  data: z.unknown()
}).strict();

export const CacheStatusOutputSchema = z.object({
  enabled: z.boolean(),
  path: z.string(),
  entries: z.number().int().nonnegative(),
  newest_cached_at: z.string().optional(),
  http_cache: z.object({
    size: z.number().int().nonnegative(),
    hit_count: z.number().int().nonnegative(),
    miss_count: z.number().int().nonnegative(),
    hit_rate: z.number().min(0).max(1),
    default_ttl_seconds: z.number().int().nonnegative(),
    bypass_env_var: z.string()
  }).strict().optional()
}).strict();

export const RevokeAccessOutputSchema = z.object({
  ok: z.boolean(),
  token_path: z.string(),
  local_tokens_cleared: z.boolean(),
  note: z.string()
}).strict();

export const PrivacyAuditOutputSchema = z.object({
  project: z.string(),
  unofficial: z.boolean(),
  config_source: z.enum(["env", "local_config", "mixed", "missing"]),
  local_config_path: z.string(),
  local_config_exists: z.boolean(),
  local_config_secure_permissions: z.boolean().optional(),
  privacy_mode_default: PrivacyModeValueSchema,
  raw_payloads_opt_in: z.boolean(),
  gps_redaction_default: z.boolean(),
  cache_enabled: z.boolean(),
  cache_path: z.string(),
  token_path: z.string(),
  stdout_safe: z.boolean(),
  secret_env_vars: z.array(z.string()),
  required_env_present: z.record(z.string(), z.boolean()),
  redacted_key_patterns: z.array(z.string()),
  notes: z.array(z.string())
}).strict();

export const CapabilitiesOutputSchema = z.object({
  project: z.string(),
  mcp_name: z.string(),
  creator: z.object({ name: z.string(), github: z.string() }).strict(),
  unofficial: z.boolean(),
  status: z.string(),
  beta_notice: z.string(),
  api_boundary: z.object({ source: z.string(), raw_definition: z.string(), does_not_include: z.array(z.string()) }).strict(),
  auth_model: z.object({ type: z.string(), token_storage: z.string(), recommended_redirect_uri: z.string(), default_scopes: z.array(z.string()), optional_read_scopes: z.array(z.string()).optional(), write_scopes: z.array(z.string()).optional() }).strict(),
  privacy_modes: z.array(z.object({ mode: PrivacyModeValueSchema, use_when: z.string() }).strict()),
  supported_data: z.array(z.object({ name: z.string(), examples: z.array(z.string()), tools: z.array(z.string()) }).strict()),
  recommended_agent_flow: z.array(z.string()),
  client_aliases: z.record(z.string(), z.unknown()),
  contribution_paths: z.array(z.string()),
  links: z.record(z.string(), z.string()),
  // Opt-in write-tool policy (FOUNDATION). Declared explicitly because the MCP SDK emits
  // additionalProperties:false for the registered output schema even on .passthrough() zod schemas.
  mutating_tools: z.object({
    policy: z.string(),
    scope_preset: z.string(),
    planned: z.array(z.string())
  }).strict().optional()
}).passthrough();

export const AgentManifestOutputSchema = z.object({
  project: z.string(),
  mcp_name: z.string(),
  client: AgentClientSchema,
  unofficial: z.boolean(),
  status: z.string(),
  beta_notice: z.string(),
  package: z.object({
    name: z.string(),
    version: z.string(),
    install_command: z.string(),
    pinned_install_command: z.string(),
    binary: z.string()
  }).strict(),
  oauth: z.object({
    provider: z.string(),
    redirect_uri: z.string(),
    scopes: z.array(z.string()),
    token_storage: z.string(),
    secret_storage: z.string()
  }).strict(),
  recommended_first_calls: z.array(z.string()),
  standard_tools: z.array(z.string()),
  resources: z.array(z.string()),
  mutating_tools: z.object({
    enabled: z.boolean(),
    write_scope: z.string(),
    scope_preset: z.string(),
    policy: z.string()
  }).strict(),
  hermes: z.object({
    config_path: z.string(),
    skill_path: z.string(),
    tool_name_prefix: z.string(),
    common_tool_names: z.array(z.string()),
    recommended_config: z.string(),
    use_direct_tools: z.boolean(),
    avoid_terminal_workarounds: z.boolean(),
    no_gateway_restart_for_data_access: z.boolean(),
    reload_after_config_change: z.string(),
    doctor_command: z.string()
  }).strict(),
  agent_rules: z.array(z.string()),
  troubleshooting: z.array(z.object({ symptom: z.string(), action: z.string() }).strict()),
  links: z.record(z.string(), z.string())
}).strict();

export const ConnectionStatusOutputSchema = z.object({
  ok: z.boolean(),
  ready_for_google_health_api: z.boolean(),
  client: AgentClientSchema.optional(),
  node: z.object({ version: z.string(), supported: z.boolean() }).strict(),
  privacy_mode: PrivacyModeValueSchema,
  required_env: z.record(z.string(), z.boolean()),
  missing_env: z.array(z.string()),
  redirect_uri: z.string().optional(),
  automatic_auth_supported: z.boolean(),
  config: z.object({ source: z.enum(["env", "local_config", "mixed", "missing"]), path: z.string(), exists: z.boolean(), secure_permissions: z.boolean().optional(), error: z.string().optional() }).strict(),
  token: z.object({ path: z.string(), exists: z.boolean(), readable: z.boolean(), permissions: z.string().optional(), secure_permissions: z.boolean().optional(), expires_at: z.number().optional(), expired: z.boolean().optional(), has_refresh_token: z.boolean().optional(), scope: z.string().optional(), error: z.string().optional() }).strict(),
  oauth: z.object({
    recommended_scopes: z.array(z.string()),
    granted_scopes: z.array(z.string()),
    missing_recommended_scopes: z.array(z.string()),
    scope_status: z.enum(["ok", "missing_recommended", "unknown", "missing_token"]),
    activity_tools_ready: z.boolean(),
    profile_tools_ready: z.boolean(),
    nutrition_write_ready: z.boolean()
  }).strict(),
  cache: z.object({ enabled: z.boolean(), path: z.string() }).strict(),
  client_checks: z.record(z.string(), z.unknown()).optional(),
  next_steps: z.array(z.string())
}).strict();

export const DataInventoryOutputSchema = z.object({
  kind: z.literal("data_inventory"),
  source: z.string(),
  mcp_name: z.string(),
  generated_at: z.string(),
  unofficial: z.boolean(),
  data_access_model: z.string(),
  auth: z.unknown().optional(),
  scopes: z.array(z.string()),
  api_boundary: z.unknown().optional(),
  privacy_modes: z.array(z.unknown()),
  categories: z.array(z.object({
    name: z.string(),
    examples: z.array(z.string()),
    tools: z.array(z.string())
  }).strict()),
  totals: z.object({
    categories: z.number().int().nonnegative(),
    listed_tools: z.number().int().nonnegative(),
    scopes: z.number().int().nonnegative()
  }).strict(),
  first_tools: z.array(z.string()),
  recommended_agent_flow: z.array(z.string()),
  links: z.record(z.string(), z.string()),
  notes: z.array(z.string())
}).strict();

export const DataTypeCatalogOutputSchema = z.object({
  kind: z.literal("data_type_catalog"),
  source: z.string(),
  official_source: z.object({
    url: z.string(),
    page_last_updated: z.string(),
    captured_at: z.string()
  }).strict(),
  generated_at: z.string(),
  note: z.string(),
  count: z.number().int().nonnegative(),
  data_types: z.array(z.object({
    slug: z.string(),
    name: z.string(),
    kind: z.string(),
    supports: z.array(z.enum(["list", "reconcile", "rollup"])),
    official_operations: z.array(z.string()),
    unit: z.string(),
    scope: z.string()
  }).strict())
}).strict();

export const CoverageOutputSchema = z.object({
  kind: z.literal("data_type_coverage"),
  mode: z.enum(["plan", "live"])
}).passthrough();

export const SummaryOutputSchema = z.object({
  kind: z.enum(["daily_summary", "weekly_summary"]),
  generated_at: z.string()
}).passthrough();

export const WellnessContextOutputSchema = z.object({
  source: z.literal("google_health"),
  generated_at: z.string(),
  recent_training_load: z.enum(["low", "normal", "high", "unknown"]),
  soreness: z.array(z.string()),
  injury_flags: z.array(z.string()),
  notes: z.array(z.string())
}).passthrough();

export type SimpleReadInput = z.infer<typeof SimpleReadInputSchema>;
export type ResponseOnlyInput = z.infer<typeof ResponseOnlyInputSchema>;
export type AgentManifestInput = z.infer<typeof AgentManifestInputSchema>;
export type AuthUrlInput = z.infer<typeof AuthUrlInputSchema>;
export type ExchangeCodeInput = z.infer<typeof ExchangeCodeInputSchema>;
export type DailySummaryInput = z.infer<typeof DailySummaryInputSchema>;
export type WellnessContextInput = z.infer<typeof WellnessContextInputSchema>;
export type WeeklySummaryInput = z.infer<typeof WeeklySummaryInputSchema>;
